export const items = [
    { id: Math.random(), title: 'breakfast', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa, minima aliquid? Velit accusamus, laborum hic magnam non mollitia nulla impedit dicta rerum dolores tenetur quae nobis laboriosam maxime, corrupti nihil!', price: '100 $', category: 'breakfast', imgUrl: "1.png" },
    { id: Math.random(), title: 'lunch', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa, minima aliquid? Velit accusamus, laborum hic magnam non mollitia nulla impedit dicta rerum dolores tenetur quae nobis laboriosam maxime, corrupti nihil!', price: '80 $', category: 'lunch', imgUrl: "2.png" },
    { id: Math.random(), title: 'dinner', description: 'Carbonara is a pasta dish made with eggs, hard cheese,  and black pepper. The dish took its modern form and name in the middle of the 20th century.The cheese is usually Pecorino Romano, parmesan, or a combination of the two. Spaghetti is the most common pasta, but fettuccine, rigatoni, linguine, or bucatini are also used. Normally guanciale or pancetta are used for the meat component.', price: '40 $', category: 'dinner', imgUrl: "desh 1.png" },
    { id: Math.random(), title: 'dinner', description: 'A Chicken parmigiana, based on a combination of the Italian parmigiana di melanzane with a cotoletta. It is widespread in North America and Australia.', price: '40 $', category: 'dinner', imgUrl: "desh 2.png" },
    { id: Math.random(), title: 'lunch VIP', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa, minima aliquid? Velit accusamus, laborum hic magnam non mollitia nulla impedit dicta rerum dolores tenetur quae nobis laboriosam maxime, corrupti nihil!', price: '30 $', category: 'lunch', imgUrl: "2.png" },
    { id: Math.random(), title: 'dinner ', description: 'An Italian-American pizza with pepperoni (salami), mushrooms, olives and peppers', price: '50 $', category: 'dinner', imgUrl: "pizzaa.png" },
    { id: Math.random(), title: 'dinner VIP PLUS ', description: 'A Chicken parmigiana, based on a combination of the Italian parmigiana di melanzane with a cotoletta. It is widespread in North America and Australia.', price: '50 $', category: 'dinner', imgUrl: "desh 3.png" },
    { id: Math.random(), title: 'breakfast', description:'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa, minima aliquid? Velit accusamus, laborum hic magnam non mollitia nulla impedit dicta rerum dolores tenetur quae nobis laboriosam maxime, corrupti nihil!', price: '50 $', category: 'breakfast', imgUrl: "3.png" },
    { id: Math.random(), title: 'snack', description: 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ipsa, minima aliquid? Velit accusamus, laborum hic magnam non mollitia nulla impedit dicta rerum dolores tenetur quae nobis laboriosam maxime, corrupti nihil!', price: '50 $', category: 'snack', imgUrl: "mac.png" }
]